when:
  - branch: main
    event: tag
  - event: manual

steps:
  - name: install depends
    image: oven/bun
    commands:
      - bun install

  - name: build
    image: reactnativecommunity/react-native-android
    volumes: [ /home/misile/al1s/cache/gradle:/woodpecker/src/github.com/NY0510/slunchv2/android/.gradle ]
    commands:
      - echo $KEYSTORE_BASE64 | base64 -di > keystore
      - echo $GOOGLE_SERVICES_JSON | base64 -di > android/app/google-services.json
      - export RN_UPLOAD_STORE_FILE=$(pwd)/keystore
      - cd android
      - ./gradlew app:assembleRelease -Dorg.gradle.parallel.threads=24
      - ./gradlew app:bundleRelease -Dorg.gradle.parallel.threads=24
      # - mkdir artifacts
      - cp "app/build/outputs/apk/release/app-release.apk" "../app.apk"
      - cp "app/build/outputs/bundle/release/app-release.aab" "../app.aab"
    environment:
      API_BASE_URL:
        from_secret: endpoint
      KEYSTORE_BASE64:
        from_secret: keystore
      RN_UPLOAD_STORE_PASSWORD:
        from_secret: keystore_password
      RN_UPLOAD_KEY_ALIAS: 'shared_keystore'
      RN_UPLOAD_KEY_PASSWORD:
        from_secret: keystore_password
      GOOGLE_SERVICES_JSON:
        from_secret: google_service
  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'app.apk'
        - 'app.aab'
        - 'sha256sum.txt'
      api_key:
        from_secret: GITHUB_API_KEY
        checksum: "sha256"
        generate-release-notes: true
        draft: true
