when:
  - branch: main
    event: tag
  - event: [manual, deployment]

steps:
  - name: install depends
    image: oven/bun
    volumes: [/home/misile/al1s/cache/node_modules:/woodpecker/src/github.com/NY0510/slunchv2/node_modules]
    commands:
      - bun install

  - name: build
    image: reactnativecommunity/react-native-android
    volumes: [/home/misile/al1s/cache/gradle:/woodpecker/src/github.com/NY0510/slunchv2/android/.gradle, /home/misile/al1s/cache/node_modules:/woodpecker/src/github.com/NY0510/slunchv2/node_modules, /home/misile/al1s/cache/global_cache:/root/.gradle]
    commands:
      - echo $KEYSTORE_BASE64 | base64 -di > keystore
      - echo $GOOGLE_SERVICES_JSON | base64 -di > android/app/google-services.json
      - echo $SENTRY_PROPERTIES | base64 -di > android/sentry.properties
      # - echo $SENTRY_PROPERTIES | base64 -di > ios/sentry.properties
      - export RN_UPLOAD_STORE_FILE=$(pwd)/keystore

      - echo "API_BASE_URL='$API_BASE_URL'" > .env
      - echo "ANDROID_HOME_BANNER_AD_UNIT_ID='$ANDROID_HOME_BANNER_AD_UNIT_ID'" >> .env
      - echo "ANDROID_NOTI_BANNER_AD_UNIT_ID='$ANDROID_NOTI_BANNER_AD_UNIT_ID'" >> .env
      - echo "ANDROID_SCHEDULE_NATIVE_AD_UNIT_ID='$ANDROID_SCHEDULE_NATIVE_AD_UNIT_ID'" >> .env
      - echo "ANDROID_MEAL_NATIVE_AD_UNIT_ID='$ANDROID_MEAL_NATIVE_AD_UNIT_ID'" >> .env
      - echo "ANDROID_NOTI_NATIVE_AD_UNIT_ID='$ANDROID_NOTI_NATIVE_AD_UNIT_ID'" >> .env

      - echo "IOS_HOME_BANNER_AD_UNIT_ID='$IOS_HOME_BANNER_AD_UNIT_ID'" >> .env
      - echo "IOS_NOTI_BANNER_AD_UNIT_ID='$IOS_NOTI_BANNER_AD_UNIT_ID'" >> .env
      - echo "IOS_SCHEDULE_NATIVE_AD_UNIT_ID='$IOS_SCHEDULE_NATIVE_AD_UNIT_ID'" >> .env
      - echo "IOS_MEAL_NATIVE_AD_UNIT_ID='$IOS_MEAL_NATIVE_AD_UNIT_ID'" >> .env
      - echo "IOS_NOTI_NATIVE_AD_UNIT_ID='$IOS_NOTI_NATIVE_AD_UNIT_ID'" >> .env

      - cd android
      - ./gradlew app:assembleRelease -Dorg.gradle.parallel.threads=48
      - ./gradlew app:bundleRelease -Dorg.gradle.parallel.threads=48
      # - mkdir artifacts
      - cp "app/build/outputs/apk/release/app-release.apk" "../app.apk"
      - cp "app/build/outputs/bundle/release/app-release.aab" "../app.aab"
    environment:
      KEYSTORE_BASE64:
        from_secret: keystore
      RN_UPLOAD_STORE_PASSWORD:
        from_secret: keystore_password
      RN_UPLOAD_KEY_ALIAS: 'shared_keystore'
      RN_UPLOAD_KEY_PASSWORD:
        from_secret: keystore_password
      GOOGLE_SERVICES_JSON:
        from_secret: google_service
      API_BASE_URL:
        from_secret: api_base_url
      SENTRY_PROPERTIES:
        from_secret: sentry_properties

      ANDROID_HOME_BANNER_AD_UNIT_ID:
        from_secret: android_home_banner_ad_unit_id
      ANDROID_NOTI_BANNER_AD_UNIT_ID:
        from_secret: android_noti_banner_ad_unit_id
      ANDROID_SCHEDULE_NATIVE_AD_UNIT_ID:
        from_secret: android_schedule_native_ad_unit_id
      ANDROID_MEAL_NATIVE_AD_UNIT_ID:
        from_secret: android_meal_native_ad_unit_id
      ANDROID_NOTI_NATIVE_AD_UNIT_ID:
        from_secret: android_noti_native_ad_unit_id

      IOS_HOME_BANNER_AD_UNIT_ID:
        from_secret: ios_home_banner_ad_unit_id
      IOS_NOTI_BANNER_AD_UNIT_ID:
        from_secret: ios_noti_banner_ad_unit_id
      IOS_SCHEDULE_NATIVE_AD_UNIT_ID:
        from_secret: ios_schedule_native_ad_unit_id
      IOS_MEAL_NATIVE_AD_UNIT_ID:
        from_secret: ios_meal_native_ad_unit_id
      IOS_NOTI_NATIVE_AD_UNIT_ID:
        from_secret: ios_noti_native_ad_unit_id
  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'app.apk'
        - 'app.aab'
        - '*sum.txt'
      api_key:
        from_secret: GITHUB_API_KEY
        checksum: 'sha256'
        generate-release-notes: true
