when:
  - branch: main
    event: tag
  - event: manual

steps:
  - name: build
    image: reactnativecommunity/react-native-android
    commands:
      - echo $KEYSTORE_BASE64 | base64 -di > keystore
      - export RN_UPLOAD_STORE_FILE=$(pwd)/keystore
      - "curl -fsSL https://bun.sh/install | bash"
      - bun install
      - cd android
      - ./gradlew assembleRelease
      - mkdir artifacts
      - cp "app/build/outputs/apk/production/release/app-release.apk" "../app.apk"
      - cp "app/build/outputs/apk/production/release/app-release.aab" "../app.aab"
    environment:
      API_BASE_URL:
        from_secret: endpoint
      KEYSTORE_BASE64:
        from_secret: keystore
      RN_UPLOAD_STORE_PASSWORD:
        from_secret: keystore_password
      RN_UPLOAD_KEY_ALIAS: "shared_keystore"
      RN_UPLOAD_KEY_PASSWORD:
        from_secret: keystore_password
  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'app.apk'
        - 'app.aab'

