on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: get artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'ny0510/slunchv2'
          version: ${{ vars.GITHUB_REF }}
          file: 'app.aab'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload to google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: kr.ny64.slunchv2
          releaseFiles: app.aab
          status: draft
  
