on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: wait for upload
        run: sleep 30

      - name: get artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'app.aab'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload to google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: kr.ny64.slunchv2
          releaseFiles: app.aab
          status: draft
          releaseName: ${{ github.event.release.tag_name }}
